#!/usr/bin/env bun
/**
 * observability.ts — viewer for the LiteLLM proxy's structured request
 * log. With `json_logs: true` in litellm.config.yaml, the proxy emits a
 * JSON record per line to stdout; start-proxy.sh redirects stdout to
 * logs/litellm.log, so the file is JSONL of mixed log events. This
 * script filters to the completed-request records and presents them in
 * a tail / costs / record view.
 *
 * Correlation note: each record carries `litellm_call_id` (a UUID
 * generated by LiteLLM). Prefer that over the upstream's `response.id`
 * for matching a request to its log entry — `response.id` is whatever
 * the upstream provider returned and varies by provider. Clients can
 * also attach a per-request `metadata.user_correlation_id` in the
 * request body; LiteLLM threads it into the record.
 *
 * Sub-commands:
 *   tail [--last N]    print the last N request records (default 20)
 *   costs              aggregate cost / tokens / count by model
 *   record <call-id>   print the full record for a specific call id
 */

import { existsSync, readFileSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const logPath = join(here, "logs", "litellm.log")

const BOLD = "\x1b[1m"
const DIM = "\x1b[2m"
const GREEN = "\x1b[32m"
const YELLOW = "\x1b[33m"
const RED = "\x1b[31m"
const CYAN = "\x1b[36m"
const RESET = "\x1b[0m"

type RequestRecord = {
  raw: any
  ts: string | null
  model: string | null
  callId: string | null
  userCorrelationId: string | null
  status: "ok" | "error" | "unknown"
  totalTokens: number | null
  promptTokens: number | null
  completionTokens: number | null
  costUsd: number | null
  durationMs: number | null
  errorMessage: string | null
}

// Defensive field lookup — LiteLLM's log shape varies by version. Each
// extractor returns the first hit from a list of plausible field paths.
function pick<T>(obj: any, paths: string[]): T | null {
  for (const p of paths) {
    let cur: any = obj
    let ok = true
    for (const seg of p.split(".")) {
      if (cur == null || typeof cur !== "object") { ok = false; break }
      cur = cur[seg]
    }
    if (ok && cur !== undefined && cur !== null) return cur as T
  }
  return null
}

function isRequestRecord(parsed: any): boolean {
  if (!parsed || typeof parsed !== "object") return false
  // A request record needs at least a model and a token count or a
  // cost. Filters out startup banners, health checks, debug logs.
  if (typeof parsed.model !== "string") return false
  if (parsed.total_tokens != null) return true
  if (parsed.response_cost != null) return true
  if (parsed.completion_tokens != null) return true
  if (parsed.usage && typeof parsed.usage === "object") return true
  return false
}

function parseRecord(parsed: any): RequestRecord {
  const status: "ok" | "error" | "unknown" =
    parsed.status === "failure" || parsed.error || parsed.exception
      ? "error"
      : parsed.status === "success" || parsed.response_cost != null || parsed.total_tokens != null
        ? "ok"
        : "unknown"
  return {
    raw: parsed,
    ts: pick(parsed, ["startTime", "start_time", "timestamp", "asctime", "time"]),
    model: pick(parsed, ["model"]),
    callId: pick(parsed, ["litellm_call_id", "call_id"]),
    userCorrelationId: pick(parsed, ["metadata.user_correlation_id", "user_correlation_id"]),
    status,
    totalTokens: pick(parsed, ["total_tokens", "usage.total_tokens"]),
    promptTokens: pick(parsed, ["prompt_tokens", "usage.prompt_tokens"]),
    completionTokens: pick(parsed, ["completion_tokens", "usage.completion_tokens"]),
    costUsd: pick(parsed, ["response_cost", "cost", "response_cost_usd"]),
    durationMs: pick(parsed, ["duration_ms", "latency_ms", "response_ms"]),
    errorMessage: pick(parsed, ["error.message", "error", "exception"]),
  }
}

function loadRecords(): RequestRecord[] {
  if (!existsSync(logPath)) return []
  const text = readFileSync(logPath, "utf-8")
  const out: RequestRecord[] = []
  for (const line of text.split("\n")) {
    const trimmed = line.trim()
    if (!trimmed.startsWith("{")) continue
    let parsed: any
    try { parsed = JSON.parse(trimmed) } catch { continue }
    if (!isRequestRecord(parsed)) continue
    out.push(parseRecord(parsed))
  }
  return out
}

function fmtCost(c: number | null): string {
  if (c == null) return DIM + "—" + RESET
  if (c < 0.0001) return c.toExponential(2)
  return "$" + c.toFixed(4)
}

function fmtTokens(t: number | null): string {
  if (t == null) return DIM + "—" + RESET
  return t.toString()
}

function fmtMs(ms: number | null): string {
  if (ms == null) return DIM + "—" + RESET
  if (ms < 1000) return `${ms}ms`
  return `${(ms / 1000).toFixed(1)}s`
}

function fmtTs(ts: string | null): string {
  if (!ts) return "—"
  // Trim to HH:MM:SS for compact display.
  const m = ts.match(/(\d{2}:\d{2}:\d{2})/)
  return m ? m[1]! : ts.slice(0, 19)
}

function cmdTail(args: string[]): void {
  let last = 20
  const i = args.indexOf("--last")
  if (i >= 0 && args[i + 1]) last = parseInt(args[i + 1]!, 10) || 20

  const records = loadRecords()
  if (records.length === 0) {
    if (!existsSync(logPath)) {
      console.log(`${YELLOW}no log at ${logPath}${RESET}`)
      console.log(`${DIM}start the proxy and send a request; records appear after the first completion.${RESET}`)
    } else {
      console.log(`${YELLOW}log file exists but contains no request records yet${RESET}`)
    }
    return
  }
  const recent = records.slice(-last)
  console.log(`${BOLD}last ${recent.length} of ${records.length} record${records.length === 1 ? "" : "s"}${RESET}  ${DIM}(${logPath})${RESET}`)
  console.log()
  console.log(
    `  ${DIM}${"time".padEnd(8)} ${"status".padEnd(6)} ${"model".padEnd(20)} ${"in→out tok".padEnd(12)} ${"latency".padEnd(8)} ${"cost".padEnd(10)} ${"call_id".padEnd(36)}${RESET}`,
  )
  for (const r of recent) {
    const ok = r.status === "ok"
    const marker = ok ? `${GREEN}ok${RESET}    ` : r.status === "error" ? `${RED}error${RESET} ` : `${YELLOW}?${RESET}     `
    const tokens = (r.promptTokens != null || r.completionTokens != null)
      ? `${fmtTokens(r.promptTokens)}→${fmtTokens(r.completionTokens)}`
      : fmtTokens(r.totalTokens)
    const callId = r.callId ?? DIM + "—" + RESET
    console.log(
      `  ${fmtTs(r.ts).padEnd(8)} ${marker} ${(r.model ?? "—").padEnd(20)} ${tokens.padEnd(12)} ${fmtMs(r.durationMs).padEnd(8)} ${fmtCost(r.costUsd).padEnd(10)} ${callId}`,
    )
    if (r.errorMessage) {
      console.log(`           ${RED}${String(r.errorMessage).slice(0, 100)}${RESET}`)
    }
  }
  console.log()
  console.log(`${DIM}view a full record:  bun run observability.ts record <call_id>${RESET}`)
}

function cmdCosts(): void {
  const records = loadRecords()
  if (records.length === 0) {
    console.log(`${YELLOW}no request records to aggregate${RESET}`)
    return
  }

  type Agg = {
    model: string
    count: number
    okCount: number
    errCount: number
    promptTokens: number
    completionTokens: number
    totalCost: number
    haveCost: boolean
  }
  const by = new Map<string, Agg>()
  for (const r of records) {
    const key = r.model ?? "—"
    if (!by.has(key)) {
      by.set(key, { model: key, count: 0, okCount: 0, errCount: 0, promptTokens: 0, completionTokens: 0, totalCost: 0, haveCost: false })
    }
    const a = by.get(key)!
    a.count += 1
    if (r.status === "ok") a.okCount += 1
    if (r.status === "error") a.errCount += 1
    if (r.promptTokens != null) a.promptTokens += r.promptTokens
    if (r.completionTokens != null) a.completionTokens += r.completionTokens
    if (r.costUsd != null) {
      a.totalCost += r.costUsd
      a.haveCost = true
    }
  }
  const rows = [...by.values()].sort((a, b) => b.totalCost - a.totalCost)
  const grandCost = rows.reduce((s, r) => s + r.totalCost, 0)
  const grandIn = rows.reduce((s, r) => s + r.promptTokens, 0)
  const grandOut = rows.reduce((s, r) => s + r.completionTokens, 0)

  console.log(`${BOLD}cost by model${RESET}  ${DIM}(${records.length} record${records.length === 1 ? "" : "s"})${RESET}`)
  console.log()
  console.log(
    `  ${DIM}${"model".padEnd(22)} ${"count".padStart(6)}  ${"ok/err".padStart(7)}  ${"in tok".padStart(10)}  ${"out tok".padStart(10)}  ${"total cost".padStart(12)}${RESET}`,
  )
  for (const r of rows) {
    const okErr = `${r.okCount}/${r.errCount}`
    const cost = r.haveCost ? "$" + r.totalCost.toFixed(4) : DIM + "—" + RESET
    console.log(
      `  ${r.model.padEnd(22)} ${r.count.toString().padStart(6)}  ${okErr.padStart(7)}  ${r.promptTokens.toString().padStart(10)}  ${r.completionTokens.toString().padStart(10)}  ${cost.padStart(12)}`,
    )
  }
  console.log()
  console.log(
    `  ${BOLD}${"total".padEnd(22)} ${rows.reduce((s, r) => s + r.count, 0).toString().padStart(6)}  ${"".padStart(7)}  ${grandIn.toString().padStart(10)}  ${grandOut.toString().padStart(10)}  ${("$" + grandCost.toFixed(4)).padStart(12)}${RESET}`,
  )
  console.log()
}

function cmdRecord(args: string[]): void {
  const id = args[0]
  if (!id) {
    console.error("record: missing call_id argument")
    process.exit(2)
  }
  const records = loadRecords()
  const hit = records.find((r) => r.callId === id || r.userCorrelationId === id)
  if (!hit) {
    console.error(`record: no record with call_id or user_correlation_id = ${id}`)
    process.exit(1)
  }
  console.log(JSON.stringify(hit.raw, null, 2))
}

const cmd = process.argv[2] ?? "tail"
const cmdArgs = process.argv.slice(3)

switch (cmd) {
  case "tail":
    cmdTail(cmdArgs)
    break
  case "costs":
    cmdCosts()
    break
  case "record":
    cmdRecord(cmdArgs)
    break
  case "--once":
    // Compat shim — wizard's "tail" menu passes --once.
    cmdTail([])
    break
  default:
    console.error(`observability: unknown sub-command '${cmd}'`)
    console.error("  try: tail [--last N]   costs   record <call_id>")
    process.exit(2)
}
